---
- hosts: all

  tasks:

  - name: stop current running container
    command: docker stop color-of-the-day-container
    ignore_errors: yes 

  - name: remove stopped container
    command: docker rm color-of-the-day-container 
    ignore_errors: yes

  - name: remove docker image
    command: docker rmi spirentdemocloud/color-of-the-day-image
    ignore_errors: yes

  - name: pull docker image from dockerhub
    command: docker pull spirentdemocloud/color-of-the-day-image

  - name: create container using color-of-day-image
    command: docker run -d --name color-of-the-day-container -p 8080:8080 spirentdemocloud/color-of-the-day-image
